Fix functionality of delete_children_matching
mpenning/ciscoconfparse pull request #244
Opened 2022-07-09 01:43 UTC by jgsawyers

Fixes two issues with delete_children_matching as reported on #241 that I just ran into myself as well. Casts the resulting iterable from filter into a list. Since it's consumed by both the list comprehension for `retval`, it was already exhausted when arriving at the `map`. Also uses to deque to consume the `map` iterable, as it's not executed until the items are iterated over. (I think this behavior changed somewhere in 3.x, it used to return a list) Could also just cast to a list of refactor to a for loop here, but I think `deque` is the fastest way to consume it.

2022-07-16 12:24 UTC, mpenning requested changes
Hello,

Thank you for your PR...

Upon reflection, using `filter()`, `map()` and `collections.dequeue()` adds pointless complexity...

Please change your PR to do this:

```python
    retval = [(obj.delete() if obj.re_search(linespec) else obj) for obj in self.children]
    return retval
```

2022-07-19 01:32 UTC, jgsawyers commented
Sure, can do. Wasn't sure if the filter\map were there for legacy reasons. I can clean up the `methodcaller` import in this PR as well if you want, looks like this was the last place it's accessed in here.

2022-07-20 00:22 UTC, mpenning commented
>  Wasn't sure if the filter\map were there for legacy reasons. I can clean up the methodcaller import in this PR as well if you want, looks like this was the last place it's accessed in here.

Please feel free to rip `methodcaller` out of `ccp_abc.py`.  Thank you...

2022-07-21 13:30 UTC, mpenning approved these changes
LGTM

2022-10-14 13:49 UTC, merged